[tool]
[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "netrix", email = "netrix89@gmail.com"},
]
dependencies = [
    "flask>=2.3.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.scripts]
start = "flask --app l2dkp.app run --debug"
